name: ibrain one website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # FTP Deploy Action with TLS/SSL encryption
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: websites/ibrain.one/
          server-dir: /home/aiwahdli/ibrain.one/
          port: 21
          protocol: ftps # Using FTPS for TLS/SSL explicit encryption
